name: Applied Software Engineering Research Group
url: #http://aserg-stela.github.io
baseurl: 

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the rouge module
highlighter: rouge

# The path structure for blog posts.
permalink: /:categories/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: academic
    name: Academic
  - key: staff
    name: Staff
  - key: postdoc
    name: Researchers
  - key: grad
    name: Graduate Students
  - key: ugrad
    name: Undergraduate Students
  - key: ugrad-alum
    name: Past Undergraduate Students
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 4

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Projects
    link: /projects.html
  - title: Publications
    link: /publications.html
#  - title: Code
#    link: /code.html
#  - title: About
#    link: /about.html